### ISSUE TITLE
Pvz Free assets are 4x4(Achievements and Main Menu)

### ISSUE THREAD

**Issue by JustMonika435** [YingFengTingYu/PopStudio#10]
After Decompiling main.rsb I found out that android version of PopStudio Making PvZ Free Assets 4x4(Achievements and Main Menu buttons)is there any way to fix this?..

**Comment by YingFengTingYu** [comment]
In PVZ Free, the Main Menu and Achievements are NOT in main.rsb. 
You can find them at "pvzfree.apk/assets/creator/Textures".
The image format is "cdat", and you can use PopStudio to convert them to PNG.

**Comment by JustMonika435** [comment]
Thanks for reply,I didn't know this,now I understand

вт, 7 февр. 2023 г., 16:05 迎风听雨 ***@***.***>:
