### ISSUE TITLE
Please help me what is this hex of Composite_List in RSB

### ISSUE THREAD

**Issue by hiepseafairy** [YingFengTingYu/PopStudio#13]
I tried make rsb packer tool,  but i'm getting a problem. 
That is I don't know what this hex means, can you tell me. Thanks.
![123](https://user-images.githubusercontent.com/125433477/218947583-060e5404-a6dc-4ffe-b26f-a5c5ed241b40.png)

**Comment by nineteendo** [comment]
That's a smart path (efficient for paths starting with the same pre-fix): https://github.com/Nineteendo/PVZ2tools/tree/master/OBBEdit#1bsr-smart-pathnames---get_name

**Comment by hiepseafairy** [comment]
I know that's smart path but it in rsb. I dont know what is 4 bytes end of name_path mean. Next 4 bytes is index number in compositelist.

**Comment by nineteendo** [comment]
Numbered group list:
```python
NAME_DICT = {}
temp = GROUP_LIST_OFFSET
file.seek(temp)
while temp < GROUP_LIST_OFFSET + GROUP_LIST_SIZE:
  GROUP_NAME = GET_NAME(file, temp, GROUP_LIST_OFFSET, NAME_DICT)
  GROUP_ID = unpack("<I", file.read(4))[0]
  temp = file.tell()
```

**Comment by hiepseafairy** [comment]
Thanks, i got it.
