### ISSUE TITLE
PAM Support

### ISSUE THREAD

**Issue by harumazzz** [YingFengTingYu/PopStudio#14]
The tool can convert PAM from version 1 to 6 to .pam.json but apparently we can't work with it. Can you make the conversion from .pam.json to xfl and back like you did with PvZ1 reanim?

**Comment by YingFengTingYu** [comment]
You need https://github.com/twinkles-twinstar/TwinStar.ToolKit

**Comment by harumazzz** [comment]
Can you give me a cheatsheet of Hex bytes in PAM, I want to create a function similar to PAM to JSON like PopStudio, thanks!

**Comment by YingFengTingYu** [comment]
> Can you give me a cheatsheet of Hex bytes in PAM, I want to create a function similar to PAM to JSON like PopStudio, thanks!

I have never made such content. You can use ilSpy to decompiled Zuma's Revenge (Windows Phone version) to see how PAM works.
