### ISSUE TITLE
Xbox 360 textures are mostly not properly scaled

### ISSUE THREAD

**Issue by LolHacksRule** [YingFengTingYu/PopStudio#19]
While the game data and textures do decode and extract correctly, a large number of the decoded textures don't look accurate when comparing the PS3 and other versions of the game. For example, this texture (images\648\credits\zuma.ptx) has dimensions 211x186 but doesn't look like the proper image with that width. There's no issues with swizzling from my testing. I encountered this problem for WMW's raw texture files and did a fix for them, it's basicly to round the output width to the nearest multiple of 64 while leaving the height the same, and I tested for this texture. Here's my fixes for reference. Any other texture with a width already having a multiple of 64 has no problem decoding. I'm not sure if this classifies as a bug but I'd rather say something than stay silent.

>if (texWidth < 64): texWidth = 64
>if (texWidth > 64 and texWidth < 128): texWidth = 128
>if (texWidth > 128 and texWidth < 192): texWidth = 192
>if (texWidth > 192 and texWidth < 256): texWidth = 256
>and so on...

![Broken](https://user-images.githubusercontent.com/30186527/225478129-cb0c1b19-2b7c-45fa-a588-3d8338c8b61a.PNG)
![Fixed](https://user-images.githubusercontent.com/30186527/225478171-c15543d7-78da-4077-86ac-81598e16ecce.png)

**Comment by YingFengTingYu** [comment]
You can choose ARGB8888_Padding when decoding/encoding ptx0 from XBox360.
![image](https://user-images.githubusercontent.com/97348874/225540738-9ca8c0e7-98d6-4fe9-8393-03559cee9f34.png)

**Comment by LolHacksRule** [comment]
Ok cool, will try tmr

**Comment by LolHacksRule** [comment]
Works perfectly. Thank you.
