### ISSUE TITLE
Building PopStudio 

### ISSUE THREAD

**Issue by harumazzz** [YingFengTingYu/PopStudio#20]
How can I build the project PopStudio, you didn't indicate that in readme.md? It seems like the version in GitHub is 6.0.0 but release is 5.0.0

**Comment by YingFengTingYu** [comment]
You can use Visual Studio 2022 to publish this project on Windows (select PopStudio.Avalonia). However, some features of PopStudio are quite unsuccessful. I am currently rewriting this project and will release it soon.
