### ISSUE TITLE
Unhandled exception

### ISSUE THREAD

**Issue by nineteendo** [YingFengTingYu/PopStudio#3]
Last login: Sun Jun 26 21:47:07 on ttys000
/Users/wannes/Downloads/MacOS4/MacOS4/osx-x64/PopStudio ; exit;
wannes@Stefans-iMac ~ % /Users/wannes/Downloads/MacOS4/MacOS4/osx-x64/PopStudio ; exit;
Unhandled exception. System.TypeInitializationException: The type initializer for 'Gtk.Application' threw an exception.
 ---> System.DllNotFoundException: Gtk: libgtk-3-0.dll, libgtk-3.so.0, libgtk-3.0.dylib, gtk-3.dll
   at GLibrary.Load(Library library)
   at Gtk.Application..cctor()
   --- End of inner exception stack trace ---
   at Gtk.Application.Init()
   at PopStudio.GTK.Program.Init()
   at PopStudio.GTK.Program.RunAppGUI()
   at PopStudio.GTK.Program.Main(String[] args)
zsh: abort      /Users/wannes/Downloads/MacOS4/MacOS4/osx-x64/PopStudio

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

**Comment by YingFengTingYu** [comment]
If you use PopStudio 4.6 on MacOS, you should install gtk+3.0. 
If you don't want to install gtk+3.0, you can use PopStudio 5.0. (I'm sorry that I've forgot to publish it. I'll publish it soon.)

**Comment by YingFengTingYu** [comment]
I've published PopStudio 5.0. You can use it on MacOS without gtk+3.0.

**Comment by nineteendo** [comment]
Alright, this seems to work now.
