### ISSUE TITLE
Does this tool support decompile cfw2 files?

### ISSUE THREAD

**Issue by katashi123** [YingFengTingYu/PopStudio#5]
Does this tool support decompile cfw2 files?

**Comment by YingFengTingYu** [comment]
This tool does not support decompiling cfw2. If you want to know the file structure of cfw2, you can decompile Zuma's Revenge! for Windows Phone.

**Comment by katashi123** [comment]
> This tool does not support decompiling cfw2. If you want to know the file structure of cfw2, you can decompile Zuma's Revenge! for Windows Phone.

thanks, but i don't have any skill to figure out the file structure.  Can you give me a hint?

**Comment by YingFengTingYu** [comment]
> > 此工具不支持反编译 cfw2。如果你想知道 cfw2 的文件结构，你可以反编译祖玛的复仇！对于 Windows Phone。
> 
> 谢谢，但我没有任何技巧来弄清楚文件结构。你能给我一个提示吗？

LolHacksRule has done it at:
https://github.com/LolHacksRule/GameFileFormatsRE/blob/main/PopCap/GeneralPopCap/PopCapCompiledFontWidget.bt
