### ISSUE TITLE
我的疑问

### ISSUE THREAD

**Issue by 6gsg** [YingFengTingYu/PopStudio#6]
感谢您的制作
但是我在使用的时候出现了一个问题
![00](https://user-images.githubusercontent.com/98737359/178154879-cde67c74-6cb4-430e-88dd-d23cb860157c.png)

**Comment by YingFengTingYu** [comment]
xnb可能具有很多类型，我的工具只支持如下类型：
1.来源于Windows Phone 8中文版植物大战僵尸的图像xnb文件，所有这类文件都使用RGBA8888纹理（一般位于image文件夹中，使用图像转码功能解码）
2.来源于Windows Phone版植物大战僵尸的动画xnb文件（一般位于reanim文件夹中，使用Reanim转码功能解码）
3.来源于Windows Phone版植物大战僵尸的粒子特效xnb文件（一般位于particles文件夹中，使用Particles转码功能解码）
4.来源于Windows Phone版植物大战僵尸的拖尾特效xnb文件（一般位于particles文件夹中，使用Trail转码功能解码）

**Comment by 6gsg** [comment]
好的,感谢解答
