### ISSUE TITLE
RTON Decode Problem!!!

### ISSUE THREAD

**Issue by maiakiaka** [YingFengTingYu/PopStudio#7]
Hi bro!
First thanks for your wonderfull tool. It help me alots. I want to contact with you but I can install QQ chat in my country. So I write here. Wish your help!
I found some Rton files when unpack Chinese PVZ2 version, but I cant decode to Json. (with international version Rton decode is good but with Chinese PVZ2 version, it failed)
Here is one of Rton files I unpacked in Chinese PVZ2 version. Please download link below
https://www.mediafire.com/file/9h6jva8qi4jmxxj/ZOMBIETYPES.RTON/file

I tried to use many tools like Popstudio, Taiji, TwinkleS Toolkit, but still failed to decode to from Rton to Json file. 
You can see failed problem in my attach file.
![Decrypt and decode failed by TwinkeS](https://user-images.githubusercontent.com/106647392/179653707-e5672e48-2463-40c4-a29b-8363d5e6f83e.png)
![Decrypt failed by Taiji](https://user-images.githubusercontent.com/106647392/179653713-32fdf3af-3045-48e8-9691-24c8ca9840dc.png)
![Encrypted RTON failed by Popstudio](https://user-images.githubusercontent.com/106647392/179653719-a19d8e20-c90c-4bc7-ad03-cdb0820f4ce7.png)
![Simple RTON decode failed by POPstudio](https://user-images.githubusercontent.com/106647392/179653723-b9c8e926-69d3-4724-acc4-d2ef6b7a6bc0.png)
![Decode failed by Taiji](https://user-images.githubusercontent.com/106647392/179653725-c0a4fbf7-737c-472b-80d8-69acedfe1c82.png)
![Decode failed by TwinkleS](https://user-images.githubusercontent.com/106647392/179653728-29f66a93-bc53-4405-84cf-609bebb3ecc5.png)

I think this failed is like Remove Header (UnityAsset Function) in Taiji Tool. But I cant understand because I just fisrt year of IT student.
Can you help me to decode this Rton file or explain me why cant decode.
Thank you very much!

**Comment by YingFengTingYu** [comment]
You need to enter the "RTON Cipher" in "Setting" page. The cipher can be found in "libSrc.so".

**Comment by maiakiaka** [comment]
Do you mean Summit RTON Ciper key in Setting page ?


Vào Th 4, 20 thg 7, 2022 vào lúc 11:48 迎风听雨 ***@***.***> đã
viết:

**Comment by YingFengTingYu** [comment]
> 

Yes. And the cipher can be found in "libSrc.so".
